# proto-file: third_party/openconfig/gnmi/proto/gnmi/gnmi.proto
# proto-message: SubscribeRequest

subscribe {
  prefix {
    origin: "openconfig"
    target: "chassis"
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "admin-status"
      }
    }
    mode: ON_CHANGE
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "ethernet"
      }
      elem {
        name: "state"
      }
      elem {
        name: "mac-address"
      }
    }
    mode: ON_CHANGE
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "hardware-port"
      }
    }
    mode: ON_CHANGE
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "health-indicator"
      }
    }
    mode: ON_CHANGE
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "id"
      }
    }
    mode: ON_CHANGE
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "oper-status"
      }
    }
    mode: ON_CHANGE
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "ethernet"
      }
      elem {
        name: "state"
      }
      elem {
        name: "port-speed"
      }
    }
    mode: ON_CHANGE
  }
  subscription {
    path {
      elem {
        name: "components"
      }
      elem {
        name: "component"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "integrated-circuit"
      }
      elem {
        name: "state"
      }
      elem {
        name: "node-id"
      }
    }
    mode: ON_CHANGE
  }
  subscription {
    path {
      elem {
        name: "components"
      }
      elem {
        name: "component"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "parent"
      }
    }
    mode: ON_CHANGE
  }
  subscription {
    path {
      elem {
        name: "components"
      }
      elem {
        name: "component"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "oper-status"
      }
    }
    mode: ON_CHANGE
  }
  subscription {
    path {
      elem {
        name: "components"
      }
      elem {
        name: "component"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "software-version"
      }
    }
    mode: ON_CHANGE
  }
  subscription {
    path {
      elem {
        name: "components"
      }
      elem {
        name: "component"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "software-module"
      }
      elem {
        name: "state"
      }
      elem {
        name: "module-type"
      }
    }
    mode: ON_CHANGE
  }
  subscription {
    path {
      elem {
        name: "system"
      }
      elem {
        name: "alarms"
      }
      elem {
        name: "alarm"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "severity"
      }
    }
    mode: ON_CHANGE
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "counters"
      }
      elem {
        name: "in-octets"
      }
    }
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "counters"
      }
      elem {
        name: "in-unicast-pkts"
      }
    }
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "counters"
      }
      elem {
        name: "in-broadcast-pkts"
      }
    }
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "counters"
      }
      elem {
        name: "in-multicast-pkts"
      }
    }
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "counters"
      }
      elem {
        name: "in-discards"
      }
    }
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "counters"
      }
      elem {
        name: "in-errors"
      }
    }
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "counters"
      }
      elem {
        name: "in-fcs-errors"
      }
    }
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "counters"
      }
      elem {
        name: "out-unicast-pkts"
      }
    }
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "counters"
      }
      elem {
        name: "out-broadcast-pkts"
      }
    }
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "counters"
      }
      elem {
        name: "out-multicast-pkts"
      }
    }
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "counters"
      }
      elem {
        name: "out-octets"
      }
    }
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "counters"
      }
      elem {
        name: "out-discards"
      }
    }
  }
  subscription {
    path {
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "counters"
      }
      elem {
        name: "out-errors"
      }
    }
  }
  subscription {
    path {
      elem {
        name: "qos"
      }
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "interface-id"
          value: "*"
        }
      }
      elem {
        name: "output"
      }
      elem {
        name: "queues"
      }
      elem {
        name: "queue"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "transmit-pkts"
      }
    }
  }
  subscription {
    path {
      elem {
        name: "qos"
      }
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "interface-id"
          value: "*"
        }
      }
      elem {
        name: "output"
      }
      elem {
        name: "queues"
      }
      elem {
        name: "queue"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "transmit-octets"
      }
    }
  }
  subscription {
    path {
      elem {
        name: "qos"
      }
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "interface-id"
          value: "*"
        }
      }
      elem {
        name: "output"
      }
      elem {
        name: "queues"
      }
      elem {
        name: "queue"
        key {
          key: "name"
          value: "*"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "dropped-pkts"
      }
    }
  }
  encoding: PROTO
}
